# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPlayground < Formula
  desc "Goreleaser playground"
  homepage "https://github.com/andrew-farries/goreleaser-playground"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.1/goreleaser-playground_Darwin_arm64.tar.gz"
      sha256 "6d9ecd68aa9c6e822fa137a9536ad2281dc8afbf82c63c4c8f1a761b92d65c5b"

      def install
        bin.install "goreleaser-playground"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.1/goreleaser-playground_Darwin_x86_64.tar.gz"
      sha256 "6ca7236e604697c56375ccdee7ecafb6844d50ccadb5479b68d5de1319b2c222"

      def install
        bin.install "goreleaser-playground"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.1/goreleaser-playground_Linux_x86_64.tar.gz"
      sha256 "f7bcd0006d2ebf73b8f979665e1d85eedde82c99fe4f682fbc92eef4953cb939"

      def install
        bin.install "goreleaser-playground"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.1/goreleaser-playground_Linux_arm64.tar.gz"
      sha256 "dfef1d803993eccdad67175e1c85cb084d08767e76cb5e61026b700b7b8cf207"

      def install
        bin.install "goreleaser-playground"
      end
    end
  end
end
