# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPlayground < Formula
  desc "Gorelease playground"
  homepage "https://github.com/andrew-farries/goreleaser-playground"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.0/goreleaser-playground_Darwin_arm64.tar.gz"
      sha256 "2e2dbb89299d55393af83d6199a313f2c5242a66b30f7e75644185c12e31f7e0"

      def install
        bin.install "goreleaser-playground"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.0/goreleaser-playground_Darwin_x86_64.tar.gz"
      sha256 "f0bcc0894b0392746c562a0d2f9cac01cd8bc6d816ac3ea92b4e6764c0d5c94e"

      def install
        bin.install "goreleaser-playground"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.0/goreleaser-playground_Linux_x86_64.tar.gz"
      sha256 "ddc97a5e6eaa282a18bf62546b6eecdd0d73a2370f76280662efdc50d96196bc"

      def install
        bin.install "goreleaser-playground"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.0/goreleaser-playground_Linux_arm64.tar.gz"
      sha256 "1a334b3171ddf50775f2237d2db82f5d94e0df1a9f41fb77a6cc3591b12c488f"

      def install
        bin.install "goreleaser-playground"
      end
    end
  end
end
