name: Release
on: [push]

permissions:
  contents: write
  packages: write

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Say hello
      run: echo hello world

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - run: git fetch --force --tags

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
